# Generated by Django 4.2.7 on 2023-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instructor', models.CharField(max_length=50)),
                ('Program_Language', models.CharField(max_length=50)),
                ('Duration_Months', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Fee', models.IntegerField()),
            ],
        ),
    ]
