# Generated by Django 4.2.7 on 2023-11-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedback1',
        ),
    ]
