# Generated by Django 4.2.7 on 2023-11-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_feedback_feedback1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback1',
            new_name='Feedback',
        ),
    ]
